# The URL the site will be built for
base_url = "https://berktold.co"

theme = "ergo"
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
highlight_code = true

[extra]
profile = "profile.jpeg" # the name of the profile picture in static/img/
color_themes = ["light"]
country_flags = true # Display languages as country flags. Defaults to false.

[[extra.socials]]
icon = "github"
display = "github"
uri = "https://github.com/JanBerktold"

[[extra.socials]]
icon = "linkedin"
display = "linkedin"
uri = "https://www.linkedin.com/in/janberktold"

[[extra.socials]]
icon = "envelope"
icon_class = "fas"
display = "say hello"
uri = "mailto:jan@berktold.co?subject=hi"

[extra.font_awesome]
kit = "e307e34624"
